
name: documentation
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

      
    - name: Install dependancies for building documentation.
      run: |
        python -m pip install --upgrade pip
        python -m pip install sphinx sphinx_rtd_theme
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


    - name: change dir to docs and run a `make html` command
      run: |
        cd docs
        make html
        ls

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: docs
        path: _build
        if-no-files-found: error
        retention-days: 20